formats:
    date:
        short:
            day: numeric
            month: long
            year: numeric

    time:
        hhmm:
            hour: numeric
            minute: numeric

    number:
        USD:
            style: currency
            currency: USD
            minimumFractionDigits: 2

    relative:
        hours:
            units: hour
            style: numeric
